baseurl = "/"
languageCode = "en-us"
title = "Scott Olesen"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:slug/"
    note = "/note/:slug/"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "publications"
    url = "/publications/"
    weight = 3
[[menu.main]]
    name = "software"
    url = "/software/"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown."
    footer = "[LinkedIn](https://www.linkedin.com/pub/scott-olesen/7a/6b3/882) | [ResearchGate](https://www.researchgate.net/profile/Scott_Olesen) | [GitHub](http://www.github.com/swo) | [RSS](/index.xml)"
