---
title: publications
author: ''
date: '2018-04-02'
slug: publications
---

**ORCID** [0000-0001-5400-4945](https://orcid.org/0000-0001-5400-4945)

**SW Olesen**, M Lipsitch, YH Grad. Outpatient antibiotic stewardship interventions: geographic scale and associations between antibiotic use and resistance. *bioRxiv* (2019). doi: [10.1101/536714](https://doi.org/10.1101/536714)

**SW Olesen**, ML Barnett, DR MacFadden, JS Brownstein, S Hernandez-Diaz, M Lipsitch, YH Grad. The distribution of antibiotic use and its association with antibiotic resistance. *eLife* 7:e39435 (2018). doi: [10.7554/eLife.39435](https://doi.org/10.7554/eLife.39435)

C Tedijanto, **SW Olesen**, YH Grad, M Lipsitch. Estimating the proportion of bystander selection for antibiotic resistance among potentially pathogenic bacterial flora. *PNAS* (2018). doi: [10.1073/pnas.1810840115](https://doi.org/10.1073/pnas.1810840115); [bioRxiv](https://www.biorxiv.org/content/early/2018/09/28/288704)

**SW Olesen**, YH Grad. Racial/ethnic disparities in antimicrobial drug use, United States, 2014-2015. *Emerging Infectious Diseases* 24(11): 2126-2128 (2018). doi: [10.3201/eid2411.180762](https://doi.org/10.3201/eid2411.180762)

K Arora-Williams, **SW Olesen**, BP Scandella, K Delwiche, SJ Spencer, EM Myers, S Abraham, A Sooklal, SP Preheim. Dynamics of microbial populations mediating biogeochemical cycling in a freshwater lake. *Microbiome* (2018) doi: [10.1186/s40168-018-0556-7](https://doi.org/10.1186/s40168-018-0556-7)

**SW Olesen**, EA Torrone, JR Papp, RD Kirkcaldy, M Lipsitch, YH Grad. Azithromycin susceptibility in *Neisseria gonorrhoeae* and seasonal macrolide use. *Journal of Infectious Diseases* (2018). doi: [10.1093/infdis/jiy551](https://doi.org/10.1093/infdis/jiy551)

**SW Olesen**, ML Barnett, DR MacFadden, M Lipsitch, YH Grad. Trends in outpatient antibiotic prescribing practice among US older adults, 2011-2015: observational study. *BMJ* (2018). doi: [10.1136/bmj.k3155](https://doi.org/10.1136/bmj.k3155); [supplement](/img/bmj_supplement.pdf)

N Wilck, MG Matus, SM Kearney, **SW Olesen**, K Forslund, H Bartolomaeus, S Haase, A Mahler, A Balogh, L Marko, O Vvedenskaya, FH Kleiner, D Tsvetkov, L Klug, PI Costea, S Sunagawa, L Maier, N Rakova, V Schatz, P Neubert, C Fratzer, A Krannich, M Gollasch, DA Grohme, BF Corte-Real, RG Gerlach, M Basic, A Typas, C Wu, JM Titze, J Jantsch, M Boschmann, R Dechend, M Kleinewietfeld, S Kempa, P Bork, RA Linker, EJ Alm, DN Muller. Salt-responsive gut commensal modules TH17 axis and disease. *Nature* (2017). doi: [10.1038/nature24628](https://doi.org/10.1038/nature24628)

**SW Olesen**, C Duvallet, EJ Alm. dbOTU3: A new implementation of distribution-based OTU calling. *PLoS ONE* 12(5): e0176335 (2017). doi: [10.1371/journal.pone.0176335](https://doi.org/10.1371/journal.pone.0176335)

**SW Olesen**\*, T Gurry\* (co-first), EJ Alm. Designing fecal microbiota  transplant trials that account for stool donor heterogeneity. *Statistical Methods in Medical Research* (2017). doi: [10.1177/0962280216688502](https://doi.org/10.1177/0962280216688502); [final pdf](http://journals.sagepub.com/doi/pdf/10.1177/0962280216688502)

SP Preheim\*, **SW Olesen**\* (co-first), A Materna, C Varadharajan, M Blackburn, J Friedman, J Rodriguez, H Hemond, EJ Alm. Surveys, simulations, and single-cell assays relate function and phylogeny in a lake ecosystem. *Nature Microbiology* 1: 16130 (2016). doi: [10.1038/nmicrobiol.2016.130](https://doi.org/10.1038/nmicrobiol.2016.130)

**Olesen SW**, Vora S, Techtmann SM, Fortney JL, Bastidas-Oyanedel JR, Rodríguez J, Hazen TC, Alm EJ. A novel analysis method for paired-sample microbial ecology experiments. *PLoS ONE* 11: e0154804 (2016). doi: [10.1371/journal.pone.0154804](https://doi.org/10.1371/journal.pone.0154804)

Smith MB, Rocha AM, Smillie CS, **Olesen SW**, Paradis C, Wu L, Campbell JH, Fortney JL, Mehlhorn TL, Lowe KA, Earles JE, Phillips J, Techtmann SM, Joyner DC, Elias DA, Bailey KL, Hurt RA, Jr, Preheim SP, Sanders MS, Yang J, Mueller MA, Brooks S, Watson DB, Zhang P, He Z, Dubinsky EA, Adams PD, Arkin AP, Fields MW, Zhou J, Alm EJ, Hazen TC. Natural bacterial communities serve as quantitative geochemical biosensors. *mBio* 6, e00326-15 (2015). doi: [10.1128/mBio.00326-15](https://doi.org/10.1128/mBio.00326-15)

**SW Olesen**, SN Fejer, D Chakrabarti, and DJ Wales. A left-handed building block self-assembles into right-and left-handed helices. *RSC Advances*, 3, 12905-12908 (2013). doi: [10.1039/C3RA41813H](https://doi.org/10.1039/C3RA41813H)

D Bingemann, MR Allen, and **SW Olesen**. Single molecules reveal the dynamics of heterogeneities in a polymer at the glass transition. *Journal of Chemical Physics*, 134, 024513 (2011). doi: [10.1063/1.3516516](https://doi.org/10.1063/1.3516516)

## Things that are not peer-reviewed papers

DR MacFadden, M Lipsitch, **SW Olesen**, Y Grad. Multidrug-resistant *Neisseria gonorrhoeae*: implications for future treatment strategies. *The Lancet Infectious Diseases* (2018). doi: [10.1016/S1473-3099(18)30274-3](https://doi.org/10.1016/S1473-3099(18)30274-3)

**SW Olesen**, ML Leier, EJ Alm, SA Kahn. Searching for superstool: maximizing the therapeutic potential of FMT. *Nature Reviews Gastroenterology & Hepatology* (2018). doi: [10.1038/s41575-018-0019-4](https://doi.org/10.1038/s41575-018-0019-4)

**SW Olesen**, EJ Alm. Dysbiosis is not an answer. *Nature Microbiology* 1: 16228 (2016). doi: [10.1038/nmicrobiol.2016.228](https://doi.org/10.1038/nmicrobiol.2016.228)

**SW Olesen**. Quantitative modeling for microbial ecology and clinical trials. PhD thesis, MIT (2016). [DSpace](https://dspace.mit.edu/handle/1721.1/107277); [source code](https://github.com/swo/mit-thesis)

**SW Olesen**. *[Processing 16S data](https://leanpub.com/primer16s/): an informal primer about 16S rRNA amplicon data*. Leanpub (2016).

**SW Olesen**, EJ Alm. "Leveraging microbes when responding to an oil spill." [HSE NOW](http://www.spe.org/hsenow/article/leveraging-microbes-when-responding-to-a-spill) (Dec 2016).

**SW Olesen**. "[What you think usearch does might not be what it does](http://microbiome.mit.edu/2016/02/07/usearch/)." MIT Center for Microbiome Informatics and Therapeutics Blog (Feb 2016).

EJ Alm and **SW Olesen**. "Genomic data and machine learning for spill response strategy." Technical memo for BP Microbiology (2015).
